### ISSUE TITLE
"See some examples" requires non-empty query [BUG]

### ISSUE THREAD

**Issue by macrakis** [opensearch-project/dashboards-search-relevance#68]
### What is the bug?
In Compare search results, "See some examples" gives an error when it shouldn't and doesn't show the Examples slide-out.

### How can one reproduce the bug?
In the Compare search results page, click in the Query box (but don't enter any text), then click on "See some examples".
It gives the error "A query is required. Enter a query." and does not show the Examples slide-out.
Clicking on "See some examples" then does display the Examples slide-out.

### What is the expected behavior?
It should not give an error, and it should show the slide-out.

### What is your host/environment?
Chrome 107.0.5304.87 on macOS 12.6 Intel

### Do you have any screenshots?
Not needed.

### Do you have any additional context?
_Any_ content in the Query field, even a single space or an invalid query, keeps this bug from happening.

**Comment by lauralexis** [comment]
Regarding the expected behavior:

It is expected to show the error, because the error is shown on blur of the field, however, it should show the slide-out.

**Comment by macrakis** [comment]
But it doesn't show the error if you never focused on the Query box at all, and just left it empty.
Or if you entered syntactically invalid JSON in the Query box.

In any case, I agree that the important thing to fix is the Examples slide-out.

**Comment by lauralexis** [comment]
We will rearrange the help text so that the link to the side panel is right aligned and above the code editor, in line with the label. The help text below the code editor will be edited as well. Brackets will also be added by default to the code editor, so that when the page loads the code editor will have brackets in it.
<img width="721" alt="Screen Shot 2022-11-08 at 11 40 46 AM" src="https://user-images.githubusercontent.com/16546056/200624818-efba52ce-9388-4d1e-8738-a0ebf3f1ae6d.png">
